import { Router } from 'express';
import * as controller from './controller.js';

const router = Router();
router.post('/', controller.create);
router.get('/', controller.list);
router.get('/atenderbem/settings', controller.atenderBemSettings);
router.get('/:deploymentId', controller.get);
router.get('/:deploymentId/events', controller.events);
router.get('/:deploymentId/stream', controller.stream);
router.post('/:deploymentId/seller-token', controller.revealSellerToken);
router.patch('/:deploymentId/units/:unitId', controller.updateUnit);
router.put('/:deploymentId/units/:unitId/atenderbem', (req, res, next) => { res.set('Cache-Control', 'no-store, private'); next(); }, controller.saveAtenderBem);
router.post('/:deploymentId/units/:unitId/atenderbem/group', (req, res, next) => { res.set('Cache-Control', 'no-store, private'); next(); }, controller.createAtenderBemGroupHandler);
router.post('/:deploymentId/units/:unitId/atenderbem/import', (req, res, next) => { res.set('Cache-Control', 'no-store, private'); next(); }, controller.startAtenderBemImportHandler);
router.post('/:deploymentId/units/:unitId/atenderbem/import/status', (req, res, next) => { res.set('Cache-Control', 'no-store, private'); next(); }, controller.checkAtenderBemImportHandler);
router.post('/:deploymentId/start', controller.start);
router.post('/:deploymentId/refresh-runs', controller.refreshRuns);
router.post('/:deploymentId/retry', controller.retry);
router.post('/:deploymentId/units/:unitId/retry', controller.retryUnit);
router.post('/:deploymentId/units/:unitId/run', controller.runUnit);
router.post('/:deploymentId/units/:unitId/activate-shadow', controller.activateShadow);
router.post('/:deploymentId/activate-tenants', controller.activateTenants);
router.post('/:deploymentId/provision-storefronts', controller.provisionStorefronts);
router.post('/:deploymentId/promote', controller.promote);
router.post('/:deploymentId/cancel', controller.cancel);
router.post('/:deploymentId/assets/presign', controller.presignAssets);
router.post('/:deploymentId/assets/confirm', controller.confirmAsset);
export default router;
